### ISSUE TITLE
Nested schema requires $id

### ISSUE THREAD

**Issue by yuatpocketgems** [ExodusMovement/schemasafe#131] opened 2020-08-07 02:06 UTC
Tested on 1.0.0-rc.1 and 1.0.0-rc.2

The following code
```javascript
const { validator } = require('@exodus/schemasafe')
validator(
    {
        "$schema": "http://json-schema.org/draft-07/schema#", 
        "properties": {
            "bar": {
                "properties": {
                    "foo": {
                        "type": "object"
                    }
                }, 
                "type": "object"
            }
        }, 
        "type": "object"
    }
)
```

throws `Unprocessed keywords: ["$id"] at #/properties/bar/properties/foo`, while ajv passes. Is this behavior intentional? If so, how do I work around it (without adding `$id` to everything)?

**Comment by ChALkeR** [comment] 2020-08-11 18:39
@yuatpocketgems I can't reproduce using the provided example. Perhaps something is missing in the sample?

**Comment by ChALkeR** [comment] 2020-08-31 12:48
I'm going to close this as there is no reply, but please feel free to comment with any additional information and I'll reopen if this can be confirmed.

**Closed by ChALkeR** 2020-08-31 12:48 UTC
Labels: blocked/needs more info
